server:
  port: 6060

spring:
  boot:
    admin:
      client:
        url: http://localhost:2333   #这里配置admin server 的地址

#开启端口
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
