server:
  port: 8888
  servlet:
    context-path: /rocketmq-producer

spring:
  application:
    name: rocketmq-producer

rocketmq:
  name-server: 192.168.1.192:9876
  producer:
    group: ${spring.application.name}
    send-message-timeout: 10000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-next-server: true
    retry-times-when-send-async-failed: 0
    retry-times-when-send-failed: 2

